# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Message Controller

# Model Form Field configuration
form: $/alekseypavlov/chat/models/messagecontroller/fields.yaml

# Model Class name
modelClass: Alekseypavlov\Chat\Models\MessageController

# Default redirect location
defaultRedirect: alekseypavlov/chat/messagecontroller

# Create page
create:
    title: Create Message Controller
    redirect: alekseypavlov/chat/messagecontroller/update/:id
    redirectClose: alekseypavlov/chat/messagecontroller

# Update page
update:
    title: Edit Message Controller
    redirect: alekseypavlov/chat/messagecontroller
    redirectClose: alekseypavlov/chat/messagecontroller

# Preview page
preview:
    title: Preview Message Controller
